
const quotesData = [{quote: "PERFECT IS THE ENEMY OF GOOD.", author: 'VOLTAIRE'},
{quote: "I'M STILL LEARNING", author: 'MICHELANGELO'},
{quote: "LIFE IS A JOURNEY, NOT A DESTINATION.", author: 'RALPH WALDO EMERSON'},
{quote: "LEARNING IS NOT ATTAINED BY CHANCE, IT MUST BE SOUGHT FOR WITH ARDOR AND ATTENDED TO WITH DILIGENCE.", author: 'ABIGAIL ADAMS'},
{quote: "YESTERDAY I WAS CLEVER, SO I CHANGED THE WORLD. TODAY I AM WISE, SO I AM CHANGING MYSELF.", author: 'RUMI'},
{quote: "BE CURIOUS, NOT JUDGMENTAL.", author: 'WALT WHITMAN'},
{quote: "YOU DON’T HAVE TO BE GREAT TO START, BUT YOU HAVE TO START TO BE GREAT.", author: 'ZIG ZIGLAR'},
{quote: "BE STUBBORN ABOUT YOUR GOALS AND FLEXIBLE ABOUT YOUR METHODS.", author: 'UNKNOWN'},
{quote: "NOTHING WILL WORK UNLESS YOU DO.", author: 'MAYA ANGELOU'},
{quote: "NEVER GIVE UP ON A DREAM JUST BECAUSE OF THE TIME IT WILL TAKE TO ACCOMPLISH IT. THE TIME WILL PASS ANYWAY.", author: 'EARL NIGHTINGALE'},
{quote: "ANYONE WHO STOPS LEARNING IS OLD, WHETHER AT TWENTY OR EIGHTY.", author: 'HENRY FORD'},
{quote: "TELL ME AND I FORGET. TEACH ME AND I REMEMBER. INVOLVE ME AND I LEARN.", author: 'BENJAMIN FRANKLIN'},
{quote: "CHANGE IS THE END RESULT OF ALL TRUE LEARNING.", author: 'LEO BUSCAGLIA'},
{quote: "LIVE AS IF YOU WERE TO DIE TOMORROW. LEARN AS IF YOU WERE TO LIVE FOREVER.", author: 'MAHATMA GANDHI'},
{quote: "A LEARNING CURVE IS ESSENTIAL TO GROWTH.", author: 'TAMMY BJELLAND'}
];

export default quotesData;